<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FFmpeg.AutoGen" Version="7.1.1" />
      <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="System.Data.SQLite.Core" Version="1.0.118" />
    </ItemGroup>

</Project>
